### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by knight42** [vhbit/rust-docset#1]
Hi, thanks for maintaining such a helpful project, but the docset hosted on AWS seems to be outdated.

The latest commit  is

```
1.11.0-nightly
a967611d8
```

See the [official site](https://doc.rust-lang.org/nightly/).

**Comment by vhbit** [comment]
Was a fluke in uploading script. Should be fixed now.

**Comment by knight42** [comment]
@vhbit The docset seems to be outdated now.
The latest version is still `0.0.4/2016-07-18-13-16`

**Comment by vhbit** [comment]
@knight42 fixed
